version: "3.8"

services:
  db_auth:
    container_name: db_auth
    restart: always
    ports: 
       - 5432:5432
    env_file: 
       - dev.env
    environment:
       PG_DATA: /var/lib/postgresql/data
    image: postgres:16.1-alpine
    volumes:
        - ./pgdata:/var/lib/postgresql/data
  app:
    working_dir: /app 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestapp
    ports:
      - '8080:8080'
    env_file: 
       - dev.env
    depends_on:
      - db_auth
    volumes:
      - ./.:/app/.
    restart: always